### ISSUE TITLE
Failed to activate the linter-spell-html package

### ISSUE THREAD

**Issue by harish123400** [yitzchak/linter-spell-html#6] opened 2017-07-13 02:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-spell-html](https://github.com/AtomLinter/linter-spell-html) package 0.6.2

### Stack Trace

Failed to activate the linter-spell-html package

```
At logger.setLevel is not a function

TypeError: logger.setLevel is not a function
    at /packages/linter-spell-html/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell-html/node_modules/natural/lib/natural/index.js:81:26)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell-html/node_modules/linter-spell-word-list/main.js:3:14)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.provideDictionary (/packages/linter-spell-html/lib/main.js:60:20)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:443:75)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:658:56
    at Set.forEach (native)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:656:47)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -3:52.5.0 core:confirm (input.hidden-input)
     -0:40.5.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
language-asp-html 0.3.0 
linter-spell-html 0.6.2 
open-html-in-browser 0.1.0 
puddletown-html-snippets 1.0.1 
```

**Comment by yitzchak** [comment] 2017-07-13 09:51
Thanks for reporting the issue. Looks like it is actually a core package issue and duplicate of  AtomLinter/linter-spell#58

Please follow there.

**Closed as completed by yitzchak** 2017-07-13 09:51 UTC
